[profile.default]
solc = "0.8.23"
src = 'contracts/src'
out = 'dist/contracts'
libs = ['contracts/lib']

via_ir = true
optimizer_runs = 1000000
eth-rpc-url = 'http://localhost:8545'

fs_permissions = [{ access = "read", path = "dist/contracts" }, { access = "read-write", path = ".forge-snapshots/" }]

extra_output = ['storageLayout']

[rpc_endpoints]
etherlink = "https://node.ghostnet.etherlink.com"
base_sepolia = "https://sepolia.base.org"

[profile.etherlink]
eth-rpc-url = "https://node.ghostnet.etherlink.com"
chain-id = 128123

[profile.base_sepolia]
eth-rpc-url = "https://sepolia.base.org"
chain-id = 84532
