[package]
name = "unite_starknet"
version = "1.0.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.8.2"

[[target.starknet-contract]]
casm = true

[scripts]
test = "scarb test"
build = "scarb build"
fmt = "scarb fmt"
