[package]
name = "unite_starknet"
version = "1.0.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.8.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.17.0" }

[[target.starknet-contract]]
casm = true
build-external-contracts = [
    "openzeppelin::token::erc20::erc20::ERC20",
    "openzeppelin::access::ownable::ownable::Ownable",
    "openzeppelin::security::reentrancyguard::reentrancyguard::ReentrancyGuard"
]

[scripts]
test = "scarb test"
build = "scarb build"
fmt = "scarb fmt"
