[package]
name = "unite-aptos"
version = "1.0.0"
authors = ["Unite Protocol"]

[addresses]
aptos_addr = "0x4d876adc1d506882f9abf11231c2dbaaa7ec5e32fba5a97b00caf26cef9596fc"

[dev-addresses]
test_addr = "0x4d876adc1d506882f9abf11231c2dbaaa7ec5e32fba5a97b00caf26cef9596fc"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]